websocket:
    endpoint: "ws://ckb-node.internal:8114"
    retry_interval: 5
    max_retries: 10
    ping_interval: 30

mqtt:
    broker: "mqtt.internal"
    port: 1883
    topic: "ckb.transactions.prod"
    client_id: "thresh-monitor-prod"
    qos: 2
    reconnect_delay: 5
    batch_size: 100

processing:
    workers: 8
    queue_size: 10000
